version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: ride_share_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongo_container
    ports:
      - "27017:27017"
    networks:
      - backend
  app:
    build: .
    depends_on:
      - postgres
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ride_share_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/ride_share_db


networks:
  backend:
